FROM golang:1.19-alpine3.16

ENV APP_NAME=CatPicHub
ENV SRC_DIR=/go/src/github.com/Codecademy/$APP_NAME
ENV GIT_COMMIT_HASH="dev"
ENV GO111MODULE=on
ENV CATPICHUB_USERNAME="catpichub_admin"
ENV CATPICHUB_PASSWORD="catpichub_password"
ENV DATABASE_USERNAME="catpichub"
ENV DATABASE_PASSWORD="catpichub@1234"

WORKDIR $SRC_DIR
ADD . $SRC_DIR

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

RUN set -eux && \
    apk add --no-cache git bash su-exec && \
    addgroup -S appuser && \
    adduser -S appuser -G appuser && \
    go mod vendor && \
    CGO_ENABLED=0 GOOS=linux go build -ldflags "-X main.AppVersion=$GIT_COMMIT_HASH" -o /bin/migrate ./migrations && \
    CGO_ENABLED=0 GOOS=linux go build -ldflags "-X main.AppVersion=$GIT_COMMIT_HASH" -o /bin/$APP_NAME ./cmd/

EXPOSE 8080

RUN chmod +x entrypoint.sh

CMD /wait && sh entrypoint.sh